---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "golang"

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ruby"

  - package-ecosystem: terraform
    directory: "/terraform"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "terraform"
