aws_account                     = "prod"
bosh_db_multi_az                = "true"
bosh_db_backup_retention_period = "35"
bosh_db_skip_final_snapshot     = "false"
bosh_db_maintenance_window      = "Thu:06:00-Thu:07:00"

concourse_db_multi_az                = "true"
concourse_db_backup_retention_period = "35"
concourse_db_skip_final_snapshot     = "false"
concourse_db_maintenance_window      = "Thu:06:00-Thu:07:00"
