aws_account = "staging"
system_dns_zone_id = "ZPFAUK62IO6DS"
bosh_db_multi_az = "true"
bosh_db_backup_retention_period = "35"
bosh_db_skip_final_snapshot = "false"
bosh_db_maintenance_window = "Wed:03:00-Wed:04:00"
