---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ghcr.io/alphagov/paas/bosh-cli-v2
    tag: 540813b98e23f9865b33c206a840a8d5633287e9
inputs:
  - name: bosh-vars-store
    optional: true
  - name: paas-bootstrap
  - name: terraform-outputs
  - name: bosh-secrets
  - name: bosh-ca
  - name: bosh-uaa-google-oauth-secrets
  - name: bosh-cyber-secrets
  - name: unix-users-ops-file
  - name: uaa-users-ops-file
outputs:
  - name: bosh-manifest
  - name: bosh-vars-store-updated
params:
  USE_VARS_STORE:
  DEPLOY_ENV:
  AWS_ACCOUNT:
  AWS_DEFAULT_REGION:
  SYSTEM_DNS_ZONE_NAME:
  BOSH_FQDN:
  BOSH_FQDN_EXTERNAL:
  BOSH_INSTANCE_PROFILE:
run:
  path: sh
  args:
    - -e
    - -c
    - |
      mkdir -p certs
      tar -xvzf bosh-ca/bosh-CA.tar.gz -C certs

      if { [ -z "$USE_VARS_STORE" ] && [ -d bosh-vars-store ]; } \
        || { [ -n "$USE_VARS_STORE" ] && [ "$USE_VARS_STORE" != "0" ] && [ "$USE_VARS_STORE" != "false" ]; } ; then
        cp bosh-vars-store/bosh-vars-store.yml bosh-vars-store-updated/bosh-vars-store.yml
        export VARS_STORE=bosh-vars-store-updated/bosh-vars-store.yml
      fi

      paas-bootstrap/manifests/bosh-manifest/scripts/generate-manifest.sh \
        > bosh-manifest/bosh-manifest.yml
