
- type: replace
  path: /variables/name=mbus_bootstrap_ssl/options/alternative_names/-
  value: ((bosh_fqdn))

- type: replace
  path: /variables/name=mbus_bootstrap_ssl/options/alternative_names/-
  value: ((bosh_fqdn_external))
