- type: replace
  path: /instance_groups/name=bosh/properties/blobstore
  value:
    provider: s3
    credentials_source: env_or_profile
    bucket_name: ((bosh_blobstore_bucket_name))
    s3_region: ((region))

- type: remove
  path: /instance_groups/name=bosh/properties/agent/env

- type: remove
  path: /instance_groups/name=bosh/jobs/name=blobstore

- type: remove
  path: /variables/name=blobstore_ca

- type: remove
  path: /variables/name=blobstore_server_tls

- type: replace
  path: /instance_groups/name=bosh/properties/agent/env?/bosh/blobstores?/-
  value:
    provider: s3
    options:
      bucket_name: ((bosh_blobstore_bucket_name))
      credentials_source: env_or_profile
      region: ((region))