- type: replace
  path: /instance_groups/name=bosh/properties/aws/max_retries?
  value: 16

# We cache the cpi compile in the bosh-cli-v2 docker image.
# You should update the cpi version here first.
# See: https://github.com/alphagov/paas-docker-cloudfoundry-tools/blob/main/bosh-cli-v2/Dockerfile
# If a different version is used in the image versus the below you will add 3-4 mins to the deploy time.

- path: /releases/name=bosh-aws-cpi
  type: replace
  value:
    name: "bosh-aws-cpi"
    version: "101"
    url: "https://bosh.io/d/github.com/cloudfoundry/bosh-aws-cpi-release?v=101"
    sha1: "12d320570e00636f1e455e588e0462465b02d86a"
