- type: replace
  path: /instance_groups/name=bosh/properties/aws/max_retries?
  value: 16

- path: /releases/name=bosh-aws-cpi
  type: replace
  value:
    name: "bosh-aws-cpi"
    version: "91"
    url: "https://bosh.io/d/github.com/cloudfoundry/bosh-aws-cpi-release?v=91"
    sha1: "c8fdf45dd3baa0c85f5f64b472b55b2ff3432cb4"
