---

- type: replace
  path: /releases/-
  value:
    name: awslogs
    version: 0.1.8
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/awslogs-0.1.8.tgz
    sha1: f2a5fc665b8d6581c302bc90aaa49a7ccd72efb9

- type: replace
  path: /instance_groups/name=bosh/jobs?/-
  value:
    name: awslogs-jammy
    release: awslogs
    properties:
      awslogs-jammy:
        region: ((region))
        awslogs_files_config:

          - name: /var/vcap/sys/log/credhub/credhub_security_events.log
            file: /var/vcap/sys/log/credhub/credhub_security_events.log
            log_group_name: bosh_d_credhub_security_events_((deploy_env))
            log_stream_name: "{{instance_id}}"
            initial_position: start_of_file
            datetime_format: "%Y-%m-%dT%H:%M:%S"

          - name: /var/vcap/sys/log/uaa/uaa_events.log
            file: /var/vcap/sys/log/uaa/uaa_events.log
            log_group_name: bosh_d_uaa_events_((deploy_env))
            log_stream_name: "{{instance_id}}"
            initial_position: start_of_file
            datetime_format: "%Y-%m-%dT%H:%M:%S"

          - name: /var/vcap/sys/log/director/audit.log
            file: /var/vcap/sys/log/director/audit.log
            log_group_name: bosh_d_audit_((deploy_env))
            log_stream_name: "{{instance_id}}"
            initial_position: start_of_file
            datetime_format: "%Y-%m-%dT%H:%M:%S"

          - name: /var/vcap/sys/log/director/audit_worker.log
            file: /var/vcap/sys/log/director/audit_worker*.log
            log_group_name: bosh_d_audit_worker_((deploy_env))
            log_stream_name: "{{instance_id}}"
            initial_position: start_of_file
            datetime_format: "%Y-%m-%dT%H:%M:%S"

          - name: /var/log/auth.log
            file: /var/log/auth.log
            log_group_name: bosh_d_auth_((deploy_env))
            log_stream_name: "{{instance_id}}"
            initial_position: start_of_file
            datetime_format: "%Y-%m-%dT%H:%M:%S"

          - name: /var/log/audit/audit.log
            file: /var/log/audit/audit.log
            log_group_name: bosh_d_kauditd_((deploy_env))
            log_stream_name: "{{instance_id}}"
            initial_position: start_of_file
            datetime_format: "%Y-%m-%dT%H:%M:%S"

- type: replace
  path: /instance_groups/name=bosh/jobs/name=uaa/properties/uaa/clients/bosh_auditor?
  value:
    override: true
    authorized-grant-types: client_credentials
    scope: ""
    authorities: bosh.read
    secret: ((bosh_auditor_password))

- type: replace
  path: /variables/-
  value:
    name: bosh_auditor_password
    type: password

- type: replace
  path: /releases/-
  value:
    name: observability
    version: 0.1.9
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/observability-0.1.9.tgz
    sha1: 23a18fe6431a36f5143ab52111843cd93863f50a

- type: replace
  path: /instance_groups/name=bosh/jobs?/-
  value:
    name: bosh-auditor
    release: observability
    properties:
      lookback_duration: 24h
      deploy_env: ((deploy_env))

      fetcher:
        bosh_client_id: bosh_auditor
        bosh_client_secret: ((bosh_auditor_password))

        bosh_ca_cert: ((default_ca.certificate))
        uaa_ca_cert: ((default_ca.certificate))

        bosh_url: https://((bosh_fqdn)):25555
        uaa_url: https://((bosh_fqdn)):8443

      shippers:
        splunk:
          hec_endpoint: https://http-inputs-gds.splunkcloud.com/services/collector
          token: ((bosh_auditor_splunk_hec_token))
